In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../indirect_ensemble_paths.csv")

In [4]:
df.head()

,edge,cause,effect,path,intermediaries,path_length,FCI_fisherz_knn_indicator_v2,FCI_fisherz_simple_indicator_v2,FCI_fisherz_simple_v2,FCI_mv_fisherz_raw_v2,PC_fisherz_knn_indicator_v2,PC_fisherz_simple_indicator_v2,PC_fisherz_simple_v2,PC_mv_fisherz_raw_v2,agreement_score
0,FiO2_max --> blood_pressure_min_missing,FiO2_max,blood_pressure_min_missing,FiO2_max --> lactate_max_missing --> blood_pre...,lactate_max_missing,2,0,0,0,0,1,0,0,0,1
1,FiO2_max --> heart_rate_max,FiO2_max,heart_rate_max,FiO2_max --> spO2_min --> heart_rate_max,spO2_min,2,0,0,0,0,1,1,0,0,2
2,FiO2_max --> heart_rate_max,FiO2_max,heart_rate_max,FiO2_max --> lactate_max_missing --> blood_pre...,lactate_max_missing --> blood_pressure_min_mis...,3,0,0,0,0,1,0,0,0,1
3,FiO2_max --> heart_rate_max,FiO2_max,heart_rate_max,FiO2_max --> lactate_max_missing --> blood_pre...,lactate_max_missing --> blood_pressure_min_mis...,4,0,0,0,0,1,0,0,0,1
4,FiO2_max --> heart_rate_max,FiO2_max,heart_rate_max,FiO2_max --> lactate_max_missing --> vaso_give...,lactate_max_missing --> vaso_given,3,0,0,0,0,1,0,0,0,1

In [5]:
aki_to_mech =df[
    (df["cause"] == "aki_24h_onset_stage_y") &
    (df["effect"] == "mechvent_post24h")
].sort_values("agreement_score", ascending=False)
aki_to_mech

,edge,cause,effect,path,intermediaries,path_length,FCI_fisherz_knn_indicator_v2,FCI_fisherz_simple_indicator_v2,FCI_fisherz_simple_v2,FCI_mv_fisherz_raw_v2,PC_fisherz_knn_indicator_v2,PC_fisherz_simple_indicator_v2,PC_fisherz_simple_v2,PC_mv_fisherz_raw_v2,agreement_score
522,aki_24h_onset_stage_y --> mechvent_post24h,aki_24h_onset_stage_y,mechvent_post24h,aki_24h_onset_stage_y --> aki_post24h_stage --...,aki_post24h_stage,2,0,0,0,0,1,1,0,1,3
523,aki_24h_onset_stage_y --> mechvent_post24h,aki_24h_onset_stage_y,mechvent_post24h,aki_24h_onset_stage_y --> blood_pressure_min_m...,blood_pressure_min_missing,2,0,0,0,0,1,1,0,0,2
524,aki_24h_onset_stage_y --> mechvent_post24h,aki_24h_onset_stage_y,mechvent_post24h,aki_24h_onset_stage_y --> inr_max --> aki_post...,inr_max --> aki_post24h_stage,3,0,0,0,0,1,1,0,0,2
525,aki_24h_onset_stage_y --> mechvent_post24h,aki_24h_onset_stage_y,mechvent_post24h,aki_24h_onset_stage_y --> bilirubin_max --> in...,bilirubin_max --> inr_max --> aki_post24h_stage,4,0,0,0,0,0,1,0,0,1
526,aki_24h_onset_stage_y --> mechvent_post24h,aki_24h_onset_stage_y,mechvent_post24h,aki_24h_onset_stage_y --> blood_pressure_min -...,blood_pressure_min --> vaso_given --> FiO2_max...,6,0,0,0,0,1,0,0,0,1
527,aki_24h_onset_stage_y --> mechvent_post24h,aki_24h_onset_stage_y,mechvent_post24h,aki_24h_onset_stage_y --> inr_max --> blood_pr...,inr_max --> blood_pressure_min --> vaso_given ...,7,0,0,0,0,1,0,0,0,1
528,aki_24h_onset_stage_y --> mechvent_post24h,aki_24h_onset_stage_y,mechvent_post24h,aki_24h_onset_stage_y --> platelet_max --> mec...,platelet_max,2,0,0,0,0,0,0,1,0,1

In [6]:
mech_to_aki = df[
    (df["cause"] == "mechvent_24h_onset") &
    (df["effect"] == "aki_post24h_stage")
].sort_values("agreement_score", ascending=False)
mech_to_aki

,edge,cause,effect,path,intermediaries,path_length,FCI_fisherz_knn_indicator_v2,FCI_fisherz_simple_indicator_v2,FCI_fisherz_simple_v2,FCI_mv_fisherz_raw_v2,PC_fisherz_knn_indicator_v2,PC_fisherz_simple_indicator_v2,PC_fisherz_simple_v2,PC_mv_fisherz_raw_v2,agreement_score
2187,mechvent_24h_onset --> aki_post24h_stage,mechvent_24h_onset,aki_post24h_stage,mechvent_24h_onset --> mechvent_post24h --> ak...,mechvent_post24h,2,0,0,0,1,0,0,1,0,2
2188,mechvent_24h_onset --> aki_post24h_stage,mechvent_24h_onset,aki_post24h_stage,mechvent_24h_onset --> bilirubin_max --> aki_p...,bilirubin_max,2,0,0,0,0,0,0,1,0,1
2189,mechvent_24h_onset --> aki_post24h_stage,mechvent_24h_onset,aki_post24h_stage,mechvent_24h_onset --> inr_max --> aki_post24h...,inr_max,2,0,0,0,0,0,0,1,0,1
2190,mechvent_24h_onset --> aki_post24h_stage,mechvent_24h_onset,aki_post24h_stage,mechvent_24h_onset --> inr_max --> bilirubin_m...,inr_max --> bilirubin_max,3,0,0,0,0,0,0,1,0,1
2191,mechvent_24h_onset --> aki_post24h_stage,mechvent_24h_onset,aki_post24h_stage,mechvent_24h_onset --> lactate_max_missing -->...,lactate_max_missing --> inr_max,3,0,0,0,0,0,1,0,0,1

In [10]:
to_aki = df[df["effect"] == "aki_24h_onset_stage_y"].sort_values("agreement_score", ascending=False)
to_aki

Empty DataFrame
Columns: [edge, cause, effect, path, intermediaries, path_length, FCI_fisherz_knn_indicator_v2, FCI_fisherz_simple_indicator_v2, FCI_fisherz_simple_v2, FCI_mv_fisherz_raw_v2, PC_fisherz_knn_indicator_v2, PC_fisherz_simple_indicator_v2, PC_fisherz_simple_v2, PC_mv_fisherz_raw_v2, agreement_score]
Index: []